// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.datacite.mds.domain.Dataset;
import org.datacite.mds.domain.Media;

privileged aspect Media_Roo_Finder {
        
}
