// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import java.lang.String;

privileged aspect Prefix_Roo_JavaBean {
    
    public String Prefix.getPrefix() {
        return this.prefix;
    }
    
    public void Prefix.setPrefix(String prefix) {
        this.prefix = prefix;
    }
    
}
