// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import org.datacite.mds.domain.AllocatorDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AllocatorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AllocatorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AllocatorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private AllocatorDataOnDemand AllocatorIntegrationTest.dod;
    
    @Test
    public void AllocatorIntegrationTest.testCountAllocators() {
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", dod.getRandomAllocator());
        long count = org.datacite.mds.domain.Allocator.countAllocators();
        org.junit.Assert.assertTrue("Counter for 'Allocator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AllocatorIntegrationTest.testFindAllocator() {
        org.datacite.mds.domain.Allocator obj = dod.getRandomAllocator();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Allocator.findAllocator(id);
        org.junit.Assert.assertNotNull("Find method for 'Allocator' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Allocator' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AllocatorIntegrationTest.testFindAllAllocators() {
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", dod.getRandomAllocator());
        long count = org.datacite.mds.domain.Allocator.countAllocators();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Allocator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.datacite.mds.domain.Allocator> result = org.datacite.mds.domain.Allocator.findAllAllocators();
        org.junit.Assert.assertNotNull("Find all method for 'Allocator' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Allocator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AllocatorIntegrationTest.testFindAllocatorEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", dod.getRandomAllocator());
        long count = org.datacite.mds.domain.Allocator.countAllocators();
        if (count > 20) count = 20;
        java.util.List<org.datacite.mds.domain.Allocator> result = org.datacite.mds.domain.Allocator.findAllocatorEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Allocator' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Allocator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void AllocatorIntegrationTest.testFlush() {
        org.datacite.mds.domain.Allocator obj = dod.getRandomAllocator();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Allocator.findAllocator(id);
        org.junit.Assert.assertNotNull("Find method for 'Allocator' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAllocator(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Allocator' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void AllocatorIntegrationTest.testMerge() {
        org.datacite.mds.domain.Allocator obj = dod.getRandomAllocator();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Allocator.findAllocator(id);
        boolean modified =  dod.modifyAllocator(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Allocator' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void AllocatorIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", dod.getRandomAllocator());
        org.datacite.mds.domain.Allocator obj = dod.getNewTransientAllocator(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Allocator' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Allocator' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void AllocatorIntegrationTest.testRemove() {
        org.datacite.mds.domain.Allocator obj = dod.getRandomAllocator();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Allocator' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Allocator.findAllocator(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Allocator' with identifier '" + id + "'", org.datacite.mds.domain.Allocator.findAllocator(id));
    }
    
}
