// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import org.datacite.mds.domain.DatasetDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DatasetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DatasetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DatasetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private DatasetDataOnDemand DatasetIntegrationTest.dod;
    
    @Test
    public void DatasetIntegrationTest.testCountDatasets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", dod.getRandomDataset());
        long count = org.datacite.mds.domain.Dataset.countDatasets();
        org.junit.Assert.assertTrue("Counter for 'Dataset' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DatasetIntegrationTest.testFindDataset() {
        org.datacite.mds.domain.Dataset obj = dod.getRandomDataset();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Dataset.findDataset(id);
        org.junit.Assert.assertNotNull("Find method for 'Dataset' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Dataset' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DatasetIntegrationTest.testFindAllDatasets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", dod.getRandomDataset());
        long count = org.datacite.mds.domain.Dataset.countDatasets();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Dataset', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.datacite.mds.domain.Dataset> result = org.datacite.mds.domain.Dataset.findAllDatasets();
        org.junit.Assert.assertNotNull("Find all method for 'Dataset' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Dataset' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DatasetIntegrationTest.testFindDatasetEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", dod.getRandomDataset());
        long count = org.datacite.mds.domain.Dataset.countDatasets();
        if (count > 20) count = 20;
        java.util.List<org.datacite.mds.domain.Dataset> result = org.datacite.mds.domain.Dataset.findDatasetEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Dataset' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Dataset' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void DatasetIntegrationTest.testFlush() {
        org.datacite.mds.domain.Dataset obj = dod.getRandomDataset();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Dataset.findDataset(id);
        org.junit.Assert.assertNotNull("Find method for 'Dataset' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataset(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Dataset' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DatasetIntegrationTest.testMerge() {
        org.datacite.mds.domain.Dataset obj = dod.getRandomDataset();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Dataset.findDataset(id);
        boolean modified =  dod.modifyDataset(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Dataset' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DatasetIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", dod.getRandomDataset());
        org.datacite.mds.domain.Dataset obj = dod.getNewTransientDataset(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Dataset' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Dataset' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void DatasetIntegrationTest.testRemove() {
        org.datacite.mds.domain.Dataset obj = dod.getRandomDataset();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dataset' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Dataset.findDataset(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Dataset' with identifier '" + id + "'", org.datacite.mds.domain.Dataset.findDataset(id));
    }
    
}
