// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import java.util.List;
import java.util.Random;
import org.datacite.mds.domain.AllocatorDataOnDemand;
import org.datacite.mds.domain.Datacentre;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DatacentreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DatacentreDataOnDemand: @Component;
    
    private Random DatacentreDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Datacentre> DatacentreDataOnDemand.data;
    
    @Autowired
    private AllocatorDataOnDemand DatacentreDataOnDemand.allocatorDataOnDemand;
    
    public Datacentre DatacentreDataOnDemand.getNewTransientDatacentre(int index) {
        org.datacite.mds.domain.Datacentre obj = new org.datacite.mds.domain.Datacentre();
        obj.setAllocator(allocatorDataOnDemand.getRandomAllocator());
        java.lang.String comments = "comments_" + index;
        if (comments.length() > 4000) {
            comments  = comments.substring(0, 4000);
        }
        obj.setComments(comments);
        obj.setContactEmail("contactEmail_" + index);
        java.lang.String contactName = "contactName_" + index;
        if (contactName.length() > 80) {
            contactName  = contactName.substring(0, 80);
        }
        obj.setContactName(contactName);
        java.lang.Integer doiQuotaAllowed = new Integer(index);
        if (doiQuotaAllowed < 0 || doiQuotaAllowed > 999999999) {
            doiQuotaAllowed = 999999999;
        }
        obj.setDoiQuotaAllowed(doiQuotaAllowed);
        java.lang.Integer doiQuotaUsed = new Integer(index);
        if (doiQuotaUsed < 0 || doiQuotaUsed > 999999999) {
            doiQuotaUsed = 999999999;
        }
        obj.setDoiQuotaUsed(doiQuotaUsed);
        java.lang.String domains = "domains_" + index;
        if (domains.length() > 255) {
            domains  = domains.substring(0, 255);
        }
        obj.setDomains(domains);
        obj.setIsActive(new Boolean(true));
        java.lang.String name = "name_" + index;
        if (name.length() > 255) {
            name  = name.substring(0, 255);
        }
        obj.setName(name);
        java.lang.String password = "password_" + index;
        if (password.length() > 30) {
            password  = password.substring(0, 30);
        }
        obj.setPassword(password);
        obj.setRoleName("roleName_" + index);
        obj.setSymbol("symbol_" + index);
        return obj;
    }
    
    public Datacentre DatacentreDataOnDemand.getSpecificDatacentre(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Datacentre obj = data.get(index);
        return Datacentre.findDatacentre(obj.getId());
    }
    
    public Datacentre DatacentreDataOnDemand.getRandomDatacentre() {
        init();
        Datacentre obj = data.get(rnd.nextInt(data.size()));
        return Datacentre.findDatacentre(obj.getId());
    }
    
    public boolean DatacentreDataOnDemand.modifyDatacentre(Datacentre obj) {
        return false;
    }
    
    public void DatacentreDataOnDemand.init() {
        data = new java.util.ArrayList<org.datacite.mds.domain.Datacentre>();
        for (int i = 0; i < 10; i++) {
            org.datacite.mds.domain.Datacentre obj = getNewTransientDatacentre(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
