// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import org.datacite.mds.domain.MetadataDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MetadataIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MetadataIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MetadataIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MetadataIntegrationTest: @Transactional;
    
    @Autowired
    private MetadataDataOnDemand MetadataIntegrationTest.dod;
    
    @Test
    public void MetadataIntegrationTest.testCountMetadatas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", dod.getRandomMetadata());
        long count = org.datacite.mds.domain.Metadata.countMetadatas();
        org.junit.Assert.assertTrue("Counter for 'Metadata' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MetadataIntegrationTest.testFindMetadata() {
        org.datacite.mds.domain.Metadata obj = dod.getRandomMetadata();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Metadata.findMetadata(id);
        org.junit.Assert.assertNotNull("Find method for 'Metadata' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Metadata' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MetadataIntegrationTest.testFindAllMetadatas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", dod.getRandomMetadata());
        long count = org.datacite.mds.domain.Metadata.countMetadatas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Metadata', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.datacite.mds.domain.Metadata> result = org.datacite.mds.domain.Metadata.findAllMetadatas();
        org.junit.Assert.assertNotNull("Find all method for 'Metadata' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Metadata' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MetadataIntegrationTest.testFindMetadataEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", dod.getRandomMetadata());
        long count = org.datacite.mds.domain.Metadata.countMetadatas();
        if (count > 20) count = 20;
        java.util.List<org.datacite.mds.domain.Metadata> result = org.datacite.mds.domain.Metadata.findMetadataEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Metadata' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Metadata' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MetadataIntegrationTest.testFlush() {
        org.datacite.mds.domain.Metadata obj = dod.getRandomMetadata();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Metadata.findMetadata(id);
        org.junit.Assert.assertNotNull("Find method for 'Metadata' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMetadata(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Metadata' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MetadataIntegrationTest.testMerge() {
        org.datacite.mds.domain.Metadata obj = dod.getRandomMetadata();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Metadata.findMetadata(id);
        boolean modified =  dod.modifyMetadata(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.datacite.mds.domain.Metadata merged = (org.datacite.mds.domain.Metadata) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Metadata' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MetadataIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", dod.getRandomMetadata());
        org.datacite.mds.domain.Metadata obj = dod.getNewTransientMetadata(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Metadata' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Metadata' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MetadataIntegrationTest.testRemove() {
        org.datacite.mds.domain.Metadata obj = dod.getRandomMetadata();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Metadata' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.Metadata.findMetadata(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Metadata' with identifier '" + id + "'", org.datacite.mds.domain.Metadata.findMetadata(id));
    }
    
}
