// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.datacite.mds.domain;

import org.datacite.mds.domain.OaiSourcesDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OaiSourcesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OaiSourcesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OaiSourcesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: OaiSourcesIntegrationTest: @Transactional;
    
    @Autowired
    private OaiSourcesDataOnDemand OaiSourcesIntegrationTest.dod;
    
    @Test
    public void OaiSourcesIntegrationTest.testCountOaiSourceses() {
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", dod.getRandomOaiSources());
        long count = org.datacite.mds.domain.OaiSources.countOaiSourceses();
        org.junit.Assert.assertTrue("Counter for 'OaiSources' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testFindOaiSources() {
        org.datacite.mds.domain.OaiSources obj = dod.getRandomOaiSources();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.OaiSources.findOaiSources(id);
        org.junit.Assert.assertNotNull("Find method for 'OaiSources' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'OaiSources' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testFindAllOaiSourceses() {
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", dod.getRandomOaiSources());
        long count = org.datacite.mds.domain.OaiSources.countOaiSourceses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'OaiSources', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.datacite.mds.domain.OaiSources> result = org.datacite.mds.domain.OaiSources.findAllOaiSourceses();
        org.junit.Assert.assertNotNull("Find all method for 'OaiSources' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'OaiSources' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testFindOaiSourcesEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", dod.getRandomOaiSources());
        long count = org.datacite.mds.domain.OaiSources.countOaiSourceses();
        if (count > 20) count = 20;
        java.util.List<org.datacite.mds.domain.OaiSources> result = org.datacite.mds.domain.OaiSources.findOaiSourcesEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'OaiSources' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'OaiSources' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testFlush() {
        org.datacite.mds.domain.OaiSources obj = dod.getRandomOaiSources();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.OaiSources.findOaiSources(id);
        org.junit.Assert.assertNotNull("Find method for 'OaiSources' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOaiSources(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'OaiSources' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testMerge() {
        org.datacite.mds.domain.OaiSources obj = dod.getRandomOaiSources();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.OaiSources.findOaiSources(id);
        boolean modified =  dod.modifyOaiSources(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.datacite.mds.domain.OaiSources merged = (org.datacite.mds.domain.OaiSources) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'OaiSources' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", dod.getRandomOaiSources());
        org.datacite.mds.domain.OaiSources obj = dod.getNewTransientOaiSources(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'OaiSources' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'OaiSources' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OaiSourcesIntegrationTest.testRemove() {
        org.datacite.mds.domain.OaiSources obj = dod.getRandomOaiSources();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OaiSources' failed to provide an identifier", id);
        obj = org.datacite.mds.domain.OaiSources.findOaiSources(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'OaiSources' with identifier '" + id + "'", org.datacite.mds.domain.OaiSources.findOaiSources(id));
    }
    
}
